### PR TITLE
Color update

### PR DESCRIPTION
**Pull request by onodip**
Changed the RGB codes of colors, trying to match the color codes from the MDO lab LaTeX style file and from the publications: 
Old colors:
image

New colors:
image

### CODE REVIEW

**Comment by JustinSGray** [comment]
actually the color change from the original publication was intentional. We switched to a more scientifically designed Tableau color scheme. See here: 
https://www.tableau.com/about/blog/2016/7/colors-upgrade-tableau-10-56782

**Comment by onodip** [comment]
Ah, okay. The color change of Optimization (purple to green) and Analysis (green to red) was also intentional?

**Comment by JustinSGray** [comment]
I have to admit that I forget the exact details of what I changed in pyXDSM. But I changed all the colors intentionally at the time. If you want to work off the tableau color scheme but use a different color->object map, I have no objection. As long as 

1) we settle on something soon 
2) consistent between pyXDSM and XDSMjs
3) We document clearly what our color scheme means somewhere

**Comment by onodip** [comment]
The intention was exactly to make pyXDSm and XDSMjs consitent. I would go for the color->object map as below, since this would loosely match the colors from the original publications, and the colors would be unique (in current pyXDSM the color for Analysis and Function is the same, so they are indistinguishable).

I already added ImplicitAnalysis to XDSMjs, which was missing there. I think the nicest would be to update the CSS in XDSMjs to match Tableau 10.

Also the style file on the [MDO Lab website
](http://mdolab.engin.umich.edu/content/xdsm-overview) could be replaced with the one in pyXDSM.

image

**Comment by JustinSGray** [comment]
Ah, I see the confusion regarding Analysis vs Function. Mathematically, there really isn't a distinction between Analysis and Function. In the original XDSM work, that amounted to the distinction between Implicitcomponent and ExplicitComponent. 

I think they should be the same color.

**Comment by onodip** [comment]
okay

**Comment by JustinSGray** [comment]
yes. I think Graeme Kennedy suggested the color selections for each block and I just went with them.

**Comment by onodip** [comment]
Okay, now I just left everything as is, with a comment that explains where the color palette is coming from. 

For the Function and Analysis there really isn't any mathematical difference, but in most examples there is a semantic difference that Analysis is used in the context of the physical problem, and Function more in context of the optimization problem formulation (as objective function, system functions for some multilevel architecture, etc.). Not sure if the XDSM wants to show this, or not.

In the XDSM writer so far I made the following mapping:

-  ExplicitComponent -> Analysis
-  ImplicitComponent -> ImplicitAnalysis
-  ExecComp, IndepVarComp -> Function

**Comment by relf** [comment]
I've just discover this discussion... I designed the initial XDSMjs css file from the original publication. My understanding of Analysis vs Function was exactly what @onodip explained. No problem to slighly  change the color map in XDSMjs but I think it is definitely best if we can match the colors of the reference publication as he suggests and as those colors have started to be known by the community. @JustinSGray, in your last (great!) OpenMDAO paper, I think you use the original colormap, isn't it? And rounded boxes for disciplines! Too bad :wink:

**Comment by JustinSGray** [comment]
Guilty as charged! Im not always as careful as I need to here here, and those XDSM's were actually not made with XDSMjs, but with an alternate script that one of the other authors had made himself. You're right that its not consistent at all, and thats true even for may MDO lab papers. 

I'll tell you what, @onodip you've put more work into this than anyone else, save Andrew Lamb (the original creator of XDSMs).  So if you want to propose the new colorscheme, I'll take what you propose to the MDOlab and we can all publish a short technical memo with and updated color scheme and and more official meaning for round vs square (im not actually sure what the difference is there myself!)

If you decline, I'll draft a color scheme myself.  Either way, its clear we need an official document on the color scheme and box meaning now :)

**Comment by onodip** [comment]
@JustinSGray challenge accepted, I will make a draft on this and share with you.

**Comment by onodip** [comment]
I suggest this color scheme, which closely resembles the original publication with the new Tableau10 colors. 

I don't really get the purpose of LP Optimization (is it Linear Programming or something else?). Also it is in a square box, whereas all the other "process coordinators" (fell free to throw in a more meaningful name, which describes both solvers & drivers) are in round boxes. So maybe I would put this "LP Optimization" in a round box with purple color (or discard it if it is not used). 

@relf you also have an MDO style in XDSMjs, which I could not find anywhere else. Is it used to concisely include a whole MDO problem (not just the optimizer itself) in the diagram (e.g. in a multilevel architecture)? In this case I think it would be useful to put it in the official styles.

image

If we can all agree on this (including the faith of "LP Optimization" and "MDO" styles), I will finish the PR and make one for the [XDSMjs ](https://github.com/OneraHub/XDSMjs) CSS.

**Comment by JustinSGray** [comment]
what do you see as the difference between `analysis` and `function` that warrants them having different colors? to me, they are the same thing (both are explicit calculations). But im open to hearing the other side of that discussion.

**Comment by onodip** [comment]
@relf and me touched upon this a few comments above. I think the distinction is useful to decouple a bit the physical/engineering model from the mathematical model. For me the Breguet range equation would be an _Analysis_, the KS constraint aggregation would be a _Function_, despite both of them can be written as an explicit function. So I think they deserve their own color. 

Otherwise why even have both of them, if they are indistinguishable on the diagram?

**Comment by JustinSGray** [comment]
I guess I would argue that they really aren't distinguishable any more. When the original XDSM publication was written, the authors separated the functionals (like surface integrations done over a wing) from the solution of the implicit equations (solving the CFD). That was their original intent, because it affected how/when you back-propogated vs solved an adjoint. 

With OpenMDAO, it generalizes a bit. Now there is just ImplicitAnalysis(Comp) vs ExplicitAnalysis(Comp), and from a mathematical point of view there is not really any distinction. 

I understand you point of wanting to separate out things that are actually physics from things that just mathematical artifice like the KS constraint. I don't think that was the original intent, since something like "drag" (a surface integral of pressure and viscous forces) would have been called a function. But if we wanted to make that distinction now, we certainly could. I can understand the argument for it. 

Personally, Im a fan of less colors just because its simpler. I would not separate out functions and metamodels. But its not a tremendously strong opinion. I can see the value there.

**Comment by relf** [comment]
@onodip, you remind me that I have also extended XDSM! You guessed well, the idea was to represent bilevel architecture. I know from @jrram they wanted to represent architectures in one diagram, but it is one thing to handcraft a diagram with nice concise math notations, it is another to generate a diagram from Python class and variable names. For the later, two diagrams are easier to implement and arguably are more readable.

For the record, I designed initially XDSMjs with Mathjax to support latex notation but the implementation was cumbersome. Finally, I’ve just implemented minimal sub and superscript capability targetting automatic generation for a web application.

**Comment by relf** [comment]
@JustinSGray, actually I am not sure to understand the initial move from the original palette. Well it is more scientific... but even with @onodip effort, I can’t help but thinking we are « breaking » existing diagrams without any significant benefit. I would even argue that the new colors are darker and provide less contrast for reading black text. That said, if @jrram and MDOlab are ok with the move it will be fine with me as soon as the reference style file, as reminded by @onodip, is updated.

**Comment by JustinSGray** [comment]
Ive reached out to @jrram and @gjkennedy for some input here. @gjkennedy is the one who originally suggested the color change, and @jrram agreed at the time. We'll see if they want to stick with it

**Comment by jrram** [comment]
First of all, a big thanks to @onodip for all the interest and effort on this, and also @JustinSGray for linking all this to OpenMDAO. I have been keeping up with this thread with interest. Here are my opinions and some other information.

* I'm not tied to the old colors or style, as long as there is a logical reason for the changes. Andrew Lambe and I iterated on this for months and there is a logical reason for (almost?) everything in there. (If you are curious, I can share with you the sequence of different versions). Having said that, this was before MAUD and more people are using XDSM, so change is warranted.

* I'm also not tied to enforcing a strict XDSM standard. People should feel free to adapt it to their own needs. Having said that, the diagrams should at least be consistent within a publication, and there should be a reason for any changes (i.e., the changes should be conscious rather than careless). I would also expect my lab to be consistent (although the standard might/will change over time).

* We should have a standard for general problems that do not use OpenMDAO, while accommodating specializations that are OpenMDAO specific.

* I like the outputs on the right. (In the original XDSM, we had them on the left.)

* On distinguishing the functions, analysis, etc. I agree with @JustinSGray on defaulting on fewer colors for simplicity. I also do not see an objective difference in the KS/Breguet example.

* I think it is valuable to distinguish implicit vs. explicit, like it's done in OpenMDAO.

* Colors: In principle Tableau 10 is better scientifically, but I agree that they ended up too dark, and not necessarily "nicer" in my opinion. I like Tableau 10 for plots, but the colors were made lighter in TikZ, which changed them considerably. Does the reasoning of the Tableau 10 colors hold after that change?

* Document: I think the changes should be documented directly on github repo in a separate md file. Will that be enough, or are we going to need a PDF file? Unfortunately I don't think this merits a paper, but if you guys really want, we could write a technical note to supplement the original paper.

* I need to update the XDSM page in the MDO Lab site. Suggestions? The files probably need to be updated...

**Comment by relf** [comment]
I like the idea of an XDSM repo (or is it pyXDSM?) where the XDSM format evolutions are tracked. It can be bootstraped with the original format (tagged 1.0?). It will prevent further misunderstanding : we (@onodip and I) took the styles.tex on the MDOlab site as the reference while it was evolving here. People will do what they want with it, but all things being equal, they will prefer to stick with a well-known convention.

**Comment by jrram** [comment]
See slides 10 through 28 to see the evolution of XDSM! Kudos to Andrew Lambe for his patience with my never ending suggestions and tweaks. If this was not done in tikz, it would have been a nightmare.
[XDSM.pdf](https://github.com/mdolab/pyXDSM/files/2942197/XDSM.pdf)

**Comment by onodip** [comment]
@jrram thanks for sharing, nice to see this evolution. In the meantime we also [started to implement ](https://github.com/OpenMDAO/OpenMDAO/pull/868) the right side output option for the OpenMDAO XDSM writer.

**Comment by JustinSGray** [comment]
I added the right side output to pyXDSM during one of my early revisions. It makes more sense to me when you have an analysis output to have it come out to the right (since thats the direction of forward data passing on the rest of the xdsm). 

I understand why you would show the optimized outputs to the left when there is an optimizer in the loop though. That also makes sense to me.

**Comment by jrram** [comment]
I like outputs to the right best (in spite of the original XDSM convention). They are more intuitive.

**Comment by JustinSGray** [comment]
ok. I think @onodip put in the most comprehensive attempt at wrangling all the styles. I agree with him that `LP_Optimization` should just match a regular optimization. I also agree that we should have a specific style for a sub-optimization block to better capture distributed optimization architectures. 

One corollary I would suggest is that we might consider having a box or separate shape for "group" vs component? Mathematically speaking,  you could have explicit vs implicit groups. so the colors would match the component ones. Perhaps a new shape? box with chamfered corners or something?

**Comment by onodip** [comment]
@JustinSGray I like the idea to distinguish between components and groups, would be nice for OpenMDAO. Maybe in pyXDSM it would be also useful, if a legend could be optionally added beneath the diagram.

For the style something like this?
image

**Comment by JustinSGray** [comment]
I would argue that the same cut-corner design would be applicable to nested optimizations as well. It indicates nested calculations in both cases.

**Comment by JustinSGray** [comment]
also, I;'ve just realized we didn't deal with one key issue. Why are there different colors for meta-model and functionals. Both of those are basically explicit calculations (though some meta-models are actually implicit... but lets just ignore that for the moment). 

So I still think that we get two colors for analysis types: explicit/implicit. Then one for solvers. One for optimizers (both of these are round). Then cut-corner styles for groups/sub-optimziations

**Comment by relf** [comment]
I agree groups and sub-optimizations can be represented with the same cut-corner style. Though I would argue that in an OpenMDAO context, you might end up with pairs of boxes solver/group. Depending on what you want to show it is ok.

Just so you can understand my mindset on that topic, in the web application I've developed I've chosen to represent group and solvers as a unique element styled with existing MDA style + italic text. And indeed even if I initially created an 'MDO style' for sub-optimizations, I came up like you did with the idea that sub-optimization representation could be built from optimization style (and italic font in my case). 

The following image illustrates my current usage of XDSM and XDSMjs on the [MultiPointBeamGroup example](http://openmdao.org/twodocs/versions/latest/examples/beam_optimization/beam_optimization_stress.html)

whatsopt-xdsm

Think about each diagram as a web page, clicking on the MDA/italic styled component moves you down in the hierarchy, clicking on the Driver component moves you up (those are links and are underlined when you hover them). Note the Driver element is an UI artifact to make visible the client of the MDA.  

@onodip, @jrram : If you're interested I can also give you an access as I did for @JustinSGray

**Comment by JustinSGray** [comment]
@relf, in the abover diagram you use a `Driver` to indicate that you can go back up the hierarchy... but there isn't a driver there. Can you use something else? how about `parent`?

**Comment by relf** [comment]
In my context, the term <code>Driver</code> is meant to specify anything that uses the MDA (i.e. a group of disciplines). Initially I named this component <code>User</code>, I changed for <code>Driver</code> certainly influenced by OpenMDAO but meaning _whatever drives/stimulates the MDA_ : obviously an OpenMDAO driver, a end user or even a solver. In that later case though, I agree it could be named <code>Parent</code> as solvers and groups are collocated in the context of OpenMDAO. 

By default XDSMjs does not manage that "Driver/User" component (to conform to the XDSM notation), I add it with specific javascript code. From my standpoint XDSMjs has to remain as simple as possible to basically display XDSM diagrams. But it should allow extension by client javascript which would implement specific UI look or interactions.

**Comment by nwu63** [comment]
Sorry to revive an old discussion, but it appears that no decisions were made at the end regarding several key questions. I think the end result we want is

1. Version tag the original repository so that we can reproduce the same diagrams as found in the original publication. Perhaps this corresponds to the existing v1.0 release?
2. Decide which objects to remove, and which objects to keep. Clearly define each object.
3. Settle on a colour palette which is somewhat consistent with the original publication, such that objects which exist in both versions are represented by similar colours. This maintains the same aesthetics and can amount to some sort of "backwards compatibility" for XDSM diagrams.
4. Tag the new version, and write up a clear standard. Perhaps keep this in a markdown file in this repo, so in a way pyXDSM will also define "the standard". This way we can keep other XDSM implementations such as XDSMjs consistent.

It seems that @onodip has put in a lot of effort on this, but I'm also happy to step in to help. To summarize the existing discussions (sorry if I forgot anything):

1. `Analysis` vs. `Function`, did we agree to remove `Function` altogether?
2. Remove `LP_Optimization` since `Optimization` should suffice
3. `Metamodel` vs. `Function`. In my mind, the use is sufficiently different that it warrants a new style, but it's not a big deal to me.
4. Adding sub-optimization as a new component?
5. Similarly, adding `Group` as another component. @JustinSGray suggested using the same colours as the `Analyses` to indicate explicit/implicit
6. Maybe I'm missing something, but the existing pyXDSM allows for outputs on either left or right side. Was the discussion on the default placement? This doesn't seem to be an issue

So there seem to be 3 open questions, plus the choice of the colour palette before we get to the new version of XDSM.

**Comment by onodip** [comment]
@nwu63, thanks for resurrecting the topic, and for summarizing.
1. I got convinced that one of them has to go. I personally would rather keep `Function`. That describes more accurately the mathematical meaning of the component. 

I think it was enough agreement on removing `LP_Optimization`, and adding `Group` and `SubOptimization`.  

For the left/right inputs I think both of them should be allowed. For me the right side is more intuitive, I would make that default.

I will try to commit the changes tomorrow, which are more or less agreed.

**Comment by relf** [comment]
@onodip, I would prefer that "left outputs" remains the default. Changing would break "backward compatibility" without any added value for me.

**Comment by nwu63** [comment]
@JustinSGray did you have time to take a look at the changes?

**Comment by JustinSGray** [comment]
These changes look ok to me. Im glad to have groups in there, though the new symbol definitely needs to be added into at least one of the examples. I would like to see the kitchen sink example adjusted to include the implicit and explicit groups, before we merged this though. 

@nwu63 I guess we'll accept the PR and then increment the version number with a new tag? 

@jrram it almost seems like an updated technical memo is in order to publish the new color scheme and additional symbols and classifications for groups. The technical memo should also detail how people should indicate which XDSM version they are using in their papers (if any). 

The one thing that I feel XDSM is now missing is some indication for linear solvers, but that does not need to go into this PR. 

Once the kitchen_sink example is updated, Id say let's accept this one with a new tag made after. the only question I have is V2 or V1.1?

**Comment by nwu63** [comment]
Yes that sounds like a good plan, update the examples then do a new tag + release.
I would say that given the scope of the changes, it probably warrants going to v2.0, though I don't feel too strongly about either way.

**Comment by JustinSGray** [comment]
@onodip can you update the kitchen_sink example to include implicit and explicit groups?

**Comment by onodip** [comment]
Updated the kitchen sink and the pictures. The version number is now 2.0, and it is included in the TeX output file, too.

**Comment by jrram** [comment]
@JustinSGray : I met with Neil and provided a suggestion on colors. Let’s see if people like them. Other than that, I like the new changes/standard. I'm not sure even a tech note would be justified. The original XDSM paper is still relevant. I think it would be sufficient to just explain the new features in the repo README.

**Comment by nwu63** [comment]
@jrram and I hashed out a new color proposal, since we felt the current one is a bit too muted.
This is the current design on the PR:
onodip_kitchen_sink

and here is our proposal:
jrram_light_kitchen_sink

We switched to the lighter version of Tableau 10 color palette, namely the Tableau 20 colors (and using the lighter variant). We also switched implicit components to red since the original colors had too many blue/green hues, and red was not used after we took out Function blocks.

What do you guys think?

**Comment by onodip** [comment]
Looks good, I like the new colors. Also makes sense with the DOE. 

@nwu63 could you make a PR on my branch or copy the piece of code defining the colors here?

**Comment by nwu63** [comment]
Since I'm a maintainer of pyXDSM, I was able to directly push to your fork. Please take a look to see if everything is in order, and maybe @JustinSGray can do the final review.

**Comment by onodip** [comment]
Okay, I updated the images, and deleted the unused color (previously for DOE).

**Pull request merged**
